/*
 * DelFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.cdw.java.recipe.Client;

import java.sql.Date;
import java.util.List;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import com.cdw.java.recipe.dao.CookDAO;
import com.cdw.java.recipe.dao.MaterialDAO;
import com.cdw.java.recipe.dao.RecipeDAO;
import com.cdw.java.recipe.dao.UserDAO;
import com.cdw.java.recipe.dao.Impl.CookDAOImpl;
import com.cdw.java.recipe.dao.Impl.MaterialDAOImpl;
import com.cdw.java.recipe.dao.Impl.RecipeDAOImpl;
import com.cdw.java.recipe.dao.Impl.UserDAOImpl;
import com.cdw.java.recipe.pojo.Recipe;

/**
 *
 * @author  __USER__
 */
public class DelFrame extends javax.swing.JFrame {
	private String nickName;
	UserDAO userDAO = new UserDAOImpl();
	RecipeDAO recipeDAO = new RecipeDAOImpl();
	MaterialDAO materialDAO = new MaterialDAOImpl();
	CookDAO cookDAO = new CookDAOImpl();
	Function fnc = new Function();

	/** Creates new form DelFrame */
	public DelFrame(String nickName) {
		this();
		this.nickName = nickName;
	}

	public DelFrame() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		txtDelId = new javax.swing.JTextField();
		jbtSend02 = new javax.swing.JButton();
		jbtReturn04 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		txtList = new javax.swing.JTextArea();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel1.setText("\u8bf7\u8f93\u5165\u8981\u5220\u9664\u7684\u83dc\u54c1\u7f16\u53f7:");

		jbtSend02.setText("\u786e\u5b9a");
		jbtSend02.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jbtSend02MouseClicked(evt);
			}
		});

		jbtReturn04.setText("\u8fd4\u56de");
		jbtReturn04.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jbtReturn04MouseClicked(evt);
			}
		});

		txtList.setColumns(20);
		txtList.setFont(new java.awt.Font("Monospaced", 0, 18));
		txtList.setForeground(new java.awt.Color(51, 0, 204));
		txtList.setRows(5);
		jScrollPane1.setViewportView(txtList);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(65, 65,
																		65)
																.addComponent(
																		jLabel1)
																.addGap(18, 18,
																		18)
																.addComponent(
																		txtDelId,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		142,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(80, 80,
																		80)
																.addComponent(
																		jbtSend02)
																.addGap(78, 78,
																		78)
																.addComponent(
																		jbtReturn04))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(24, 24,
																		24)
																.addComponent(
																		jScrollPane1,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		765,
																		Short.MAX_VALUE)))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										414,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										26, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(
														txtDelId,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jbtSend02)
												.addComponent(jbtReturn04))
								.addGap(34, 34, 34)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jbtSend02MouseClicked(java.awt.event.MouseEvent evt) {
		int rid = Integer.valueOf(this.txtDelId.getText());
		List<Recipe> recipeList = fnc.ShowMy(nickName);
		String rname = fnc.getRecipe(rid);
		boolean flag = false;
		for (Recipe recipe : recipeList) {
			int id = recipe.getId();
			if (rid == id) {
				flag = true;
				break;
			}
		}
		if (flag) {
			boolean flag1 = fnc.DelRecipe(rid);
			boolean flag2 = fnc.DelMaterial(rid);
			boolean flag3 = fnc.DelCook(rid);
			if (flag1 && flag2 || flag2 && flag3 || flag1 && flag3) {
				JOptionPane.showMessageDialog(new JFrame(), "删除成功!");
			} else {
				JOptionPane.showMessageDialog(new JFrame(), "删除失败!");
			}
		} else {
			JOptionPane.showMessageDialog(new JFrame(), "请输入列表中存在的编号!");
		}
	}

	private void jbtReturn04MouseClicked(java.awt.event.MouseEvent evt) {
		MainMenuFrame mainMenuFrame = new MainMenuFrame(nickName);
		mainMenuFrame.setTitle(nickName);
		mainMenuFrame.setVisible(true);
		this.setVisible(false);
	}

	public void DelList() {
		List<Recipe> recipeList = fnc.ShowMy(nickName);
		StringBuilder stb = new StringBuilder("编号" + "\t" + "名称" + "\t\t\t"
				+ "创建者" + "\t\t" + "上传时间" + "\r\n");
		for (Recipe recipe : recipeList) {
			int id = recipe.getId();
			String name = recipe.getName();
			Date date = recipe.getDate();
			stb.append(id + "\t" + name + "\t\t" + nickName + "\t\t" + date
					+ "\r\n");

		}
		this.txtList.setText(stb.toString());
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new DelFrame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JButton jbtReturn04;
	private javax.swing.JButton jbtSend02;
	private javax.swing.JTextField txtDelId;
	private javax.swing.JTextArea txtList;
	// End of variables declaration//GEN-END:variables

}