/*
 * Login.java
 *
 * Created on __DATE__, __TIME__
 */

package com.cdw.java.recipe.Client;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import com.cdw.java.recipe.dao.UserDAO;
import com.cdw.java.recipe.dao.Impl.UserDAOImpl;
import com.cdw.java.recipe.pojo.User;

/**
 *
 * @author  __USER__
 */
public class LoginFrame extends javax.swing.JFrame {

	/** Creates new form Login */
	public LoginFrame() {
		initComponents();
	}

	UserDAO userDAO = new UserDAOImpl();

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jButton1 = new javax.swing.JButton();
		txtLoginId = new javax.swing.JTextField();
		jbtLogin = new javax.swing.JButton();
		jbtRegist = new javax.swing.JButton();
		jbtTourist = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		txtPwd = new javax.swing.JPasswordField();

		jButton1.setText("jButton1");

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		txtLoginId.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtLoginIdActionPerformed(evt);
			}
		});

		jbtLogin.setForeground(new java.awt.Color(0, 0, 255));
		jbtLogin.setText("\u767b\u5f55");
		jbtLogin.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jbtLoginMouseClicked(evt);
			}
		});

		jbtRegist.setForeground(new java.awt.Color(0, 0, 255));
		jbtRegist.setText("\u6ce8\u518c");
		jbtRegist.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jbtRegistMouseClicked(evt);
			}
		});

		jbtTourist.setForeground(new java.awt.Color(255, 0, 0));
		jbtTourist.setText("\u6e38\u5ba2\u8eab\u4efd\u8fdb\u5165");
		jbtTourist.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jbtTouristMouseClicked(evt);
			}
		});

		jLabel1.setText("\u8d26\u53f7");

		jLabel2.setText("\u5bc6\u7801");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(140, 140, 140)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(
																						jLabel2,
																						javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel1,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						81,
																						Short.MAX_VALUE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						txtPwd,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						185,
																						Short.MAX_VALUE)
																				.addComponent(
																						txtLoginId,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						185,
																						javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jbtLogin,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		78,
																		Short.MAX_VALUE)
																.addGap(123,
																		123,
																		123)
																.addComponent(
																		jbtRegist,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		71,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGap(173, 173, 173))
				.addGroup(
						layout.createSequentialGroup()
								.addGap(214, 214, 214)
								.addComponent(jbtTourist,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										131,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(240, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(41, 41, 41)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														txtLoginId,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														43,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel1))
								.addGap(47, 47, 47)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel2)
												.addComponent(
														txtPwd,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														44,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(45, 45, 45)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jbtLogin,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														40,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jbtRegist,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														37,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(39, 39, 39)
								.addComponent(jbtTourist,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										44,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(40, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jbtTouristMouseClicked(java.awt.event.MouseEvent evt) {
		TouristFrame touristFrame = new TouristFrame();
		touristFrame.setTitle("----游客----");
		touristFrame.setVisible(true);
		this.setVisible(false);
	}

	private void jbtRegistMouseClicked(java.awt.event.MouseEvent evt) {
		RegistFrame registFrame = new RegistFrame();
		registFrame.setVisible(true);
		this.setVisible(false);

	}

	private void jbtLoginMouseClicked(java.awt.event.MouseEvent evt) {
		String loginId = txtLoginId.getText();
		String pwd = new String(txtPwd.getText());
		login(loginId, pwd);

	}

	private void login(String loginId, String pwd) {
		User user = userDAO.Login(loginId, pwd);
		if (user == null) {
			JOptionPane.showMessageDialog(new JFrame(), "用户不存在或密码不正确！");
		} else {
			MainMenuFrame mainMenuFrame = new MainMenuFrame(user.getNickName());
			mainMenuFrame.setTitle(user.getNickName());
			mainMenuFrame.setVisible(true);
			this.setVisible(false);
		}
	}

	private void txtLoginIdActionPerformed(java.awt.event.ActionEvent evt) { // TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new LoginFrame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JButton jbtLogin;
	private javax.swing.JButton jbtRegist;
	private javax.swing.JButton jbtTourist;
	private javax.swing.JTextField txtLoginId;
	private javax.swing.JPasswordField txtPwd;
	// End of variables declaration//GEN-END:variables

}