/*
 * Regist.java
 *
 * Created on __DATE__, __TIME__
 */

package com.cdw.java.recipe.Client;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import com.cdw.java.recipe.dao.UserDAO;
import com.cdw.java.recipe.dao.Impl.UserDAOImpl;
import com.cdw.java.recipe.pojo.User;

/**
 *
 * @author  __USER__
 */
public class RegistFrame extends javax.swing.JFrame {
	UserDAO userDAO=new UserDAOImpl();
	/** Creates new form Regist */
	public RegistFrame() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		txtLoginId = new javax.swing.JTextField();
		txtPwd = new javax.swing.JTextField();
		txtNickName = new javax.swing.JTextField();
		jbtRegist = new javax.swing.JButton();
		jbtReturn = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("\u8d26\u53f7");

		jLabel2.setText("\u5bc6\u7801");

		jLabel3.setText("\u6635\u79f0");

		jbtRegist.setText("\u786e\u5b9a");
		jbtRegist.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jbtRegistMouseClicked(evt);
			}
		});

		jbtReturn.setText("\u8fd4\u56de");
		jbtReturn.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jbtReturnMouseClicked(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(102, 102, 102)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jbtRegist,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		84,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		81,
																		Short.MAX_VALUE)
																.addComponent(
																		jbtReturn,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		85,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel2)
																				.addComponent(
																						jLabel1)
																				.addComponent(
																						jLabel3))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		60,
																		Short.MAX_VALUE)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				false)
																				.addComponent(
																						txtPwd,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						117,
																						Short.MAX_VALUE)
																				.addComponent(
																						txtNickName)
																				.addComponent(
																						txtLoginId,
																						javax.swing.GroupLayout.Alignment.LEADING,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						160,
																						javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addContainerGap(182, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(
														txtLoginId,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(49, 49, 49)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(
														txtPwd,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(46, 46, 46)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(
														txtNickName,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										66, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jbtRegist)
												.addComponent(jbtReturn))
								.addGap(48, 48, 48)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jbtReturnMouseClicked(java.awt.event.MouseEvent evt) {
		LoginFrame loginFrame = new LoginFrame();
		loginFrame.setVisible(true);
		this.setVisible(false);
	}

	private void jbtRegistMouseClicked(java.awt.event.MouseEvent evt) {
		String loginId = this.txtLoginId.getText();
		String pwd = this.txtPwd.getText();
		String nickName = this.txtNickName.getText();
		regist(loginId,pwd,nickName);
	}

	private void regist(String loginId, String pwd, String nickName) {
		String msg=userDAO.Regist(loginId, pwd, nickName);
		if(msg.equals("ID或昵称已被占用,请重新输入")){
			JOptionPane.showMessageDialog(new JFrame(), msg);
		}else if(msg.equals("注册失败!")){
			JOptionPane.showMessageDialog(new JFrame(), msg);
		}else{
			PopupFrame popupFrame=new PopupFrame();
			popupFrame.setTitle("提示");
			popupFrame.setVisible(true);
			this.setVisible(false);
		}
	}
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new RegistFrame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JButton jbtRegist;
	private javax.swing.JButton jbtReturn;
	private javax.swing.JTextField txtLoginId;
	private javax.swing.JTextField txtNickName;
	private javax.swing.JTextField txtPwd;
	// End of variables declaration//GEN-END:variables

}