/*
 * SearchFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.cdw.java.recipe.Client;

import java.util.Date;
import java.util.List;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import com.cdw.java.recipe.dao.CookDAO;
import com.cdw.java.recipe.dao.MaterialDAO;
import com.cdw.java.recipe.dao.RecipeDAO;
import com.cdw.java.recipe.dao.UserDAO;
import com.cdw.java.recipe.dao.Impl.CookDAOImpl;
import com.cdw.java.recipe.dao.Impl.MaterialDAOImpl;
import com.cdw.java.recipe.dao.Impl.RecipeDAOImpl;
import com.cdw.java.recipe.dao.Impl.UserDAOImpl;
import com.cdw.java.recipe.pojo.Recipe;

/**
 *
 * @author  __USER__
 */
public class SearchFrame extends javax.swing.JFrame {

	UserDAO userDAO = new UserDAOImpl();
	RecipeDAO recipeDAO = new RecipeDAOImpl();
	MaterialDAO materialDAO = new MaterialDAOImpl();
	CookDAO cookDAO = new CookDAOImpl();
	Function fnc = new Function();
	Date date = new Date();
	private String nickName;

	public SearchFrame(String nickName) {
		this();
		this.nickName = nickName;
	}

	/** Creates new form SearchFrame */
	public SearchFrame() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		txtRname = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jbtSend08 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		txtRname.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		txtRname.setForeground(new java.awt.Color(204, 0, 0));

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel1.setText("\u8bf7\u8f93\u5165\u83dc\u540d\uff1a");

		jbtSend08.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jbtSend08.setForeground(new java.awt.Color(255, 0, 0));
		jbtSend08.setText("\u641c\u7d22");
		jbtSend08.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jbtSend08MouseClicked(evt);
			}
		});
		jbtSend08.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				
			}
		});

		jButton2.setForeground(new java.awt.Color(255, 0, 0));
		jButton2.setText("\u8fd4\u56de");
		jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton2MouseClicked(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(112, 112, 112)
								.addComponent(jLabel1)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jbtSend08)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		91,
																		Short.MAX_VALUE)
																.addComponent(
																		jButton2))
												.addComponent(
														txtRname,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														223, Short.MAX_VALUE))
								.addContainerGap(141, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(119, 119, 119)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel1)
																.addContainerGap())
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		txtRname,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		37,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		44,
																		Short.MAX_VALUE)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jbtSend08,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						42,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jButton2,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						42,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(128,
																		128,
																		128)))));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jbtSend08MouseClicked(java.awt.event.MouseEvent evt) {
			String rname=this.txtRname.getText();
			List<Recipe> recipeList=fnc.ShowRecipeList(rname);
			if(!recipeList.isEmpty()){
			StringBuilder stb=new StringBuilder("编号" + "\t" + "名称" + "\t\t\t" + "创建者" + "\t\t"
					+ "上传时间" + "\r\n");
			for (Recipe recipe : recipeList) {
				int id = recipe.getId();
				String name = recipe.getName();
				String uname = recipe.getUname();
				Date date = recipe.getDate();	
				stb.append(id + "\t" + name + "\t\t" + uname + "\t\t"
						+ date+"\r\n");
			}
			String stb1=stb.toString();
				ShowAllFrame showAllFrame=new ShowAllFrame();	
				showAllFrame.showResult(stb1);
				showAllFrame.setTitle(this.getTitle());
				showAllFrame.setVisible(true);
				
			}else{
				JOptionPane.showMessageDialog(new JFrame(), "没有你要的结果！");
			}
	}

	private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {
		String title = this.getTitle();
		if (title.equals("搜索菜品")) {
			MainMenuFrame mainMenuFrame = new MainMenuFrame(nickName);
			mainMenuFrame.setTitle(nickName);
			mainMenuFrame.setVisible(true);
			this.setVisible(false);
		} else {
			TouristFrame touristFrame = new TouristFrame();
			touristFrame.setTitle("----游客----");
			touristFrame.setVisible(true);
			this.setVisible(false);
		}

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new SearchFrame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JButton jbtSend08;
	private javax.swing.JTextField txtRname;
	// End of variables declaration//GEN-END:variables

}