/*
 * ShowMyFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.cdw.java.recipe.Client;

import java.net.Socket;
import java.sql.Date;
import java.util.List;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import com.cdw.java.recipe.dao.CookDAO;
import com.cdw.java.recipe.dao.MaterialDAO;
import com.cdw.java.recipe.dao.RecipeDAO;
import com.cdw.java.recipe.dao.UserDAO;
import com.cdw.java.recipe.dao.Impl.CookDAOImpl;
import com.cdw.java.recipe.dao.Impl.MaterialDAOImpl;
import com.cdw.java.recipe.dao.Impl.RecipeDAOImpl;
import com.cdw.java.recipe.dao.Impl.UserDAOImpl;
import com.cdw.java.recipe.pojo.Recipe;

/**
 *
 * @author  __USER__
 */
public class ShowMyFrame extends javax.swing.JFrame {
	UserDAO userDAO = new UserDAOImpl();
	RecipeDAO recipeDAO = new RecipeDAOImpl();
	MaterialDAO materialDAO = new MaterialDAOImpl();
	CookDAO cookDAO = new CookDAOImpl();
	Function fnc = new Function();
	private String nickName;
	/** Creates new form ShowMyFrame */
	public ShowMyFrame(String nickName){
		this();
		this.nickName=nickName;
	}
	public ShowMyFrame() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		txtShowMy = new javax.swing.JTextArea();
		jLabel1 = new javax.swing.JLabel();
		txtRecipeId = new javax.swing.JTextField();
		jbtSend03 = new javax.swing.JButton();
		jbtReturn03 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		txtShowMy.setColumns(20);
		txtShowMy.setFont(new java.awt.Font("Monospaced", 0, 18));
		txtShowMy.setForeground(new java.awt.Color(0, 0, 204));
		txtShowMy.setRows(5);
		jScrollPane1.setViewportView(txtShowMy);

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel1.setText("\u8bf7\u8f93\u5165\u7f16\u53f7:");

		jbtSend03.setText("\u786e\u5b9a");
		jbtSend03.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jbtSend03MouseClicked(evt);
			}
		});

		jbtReturn03.setText("\u8fd4\u56de");
		jbtReturn03.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jbtReturn03MouseClicked(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(165, Short.MAX_VALUE)
								.addComponent(jLabel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										109,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addComponent(txtRecipeId,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										121,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(118, 118, 118).addComponent(jbtSend03)
								.addGap(110, 110, 110)
								.addComponent(jbtReturn03)
								.addGap(180, 180, 180))
				.addGroup(
						layout.createSequentialGroup()
								.addGap(47, 47, 47)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										844,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(56, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										369,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										35, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jbtReturn03)
												.addComponent(jbtSend03)
												.addComponent(jLabel1)
												.addComponent(
														txtRecipeId,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(39, 39, 39)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jbtReturn03MouseClicked(java.awt.event.MouseEvent evt) {
		MainMenuFrame mainMenuFrame = new MainMenuFrame(nickName);
		mainMenuFrame.setTitle(nickName);
		mainMenuFrame.setVisible(true);
		this.setVisible(false);
	}

	public void ReadList(String uname) {
		List<Recipe> recipeList = fnc.ShowMy(uname);
		
		StringBuilder stb = new StringBuilder("编号" + "\t" + "名称" + "\t\t\t"
				+ "创建者" + "\t\t" + "上传时间" + "\r\n");
		for (Recipe recipe : recipeList) {
			int id = recipe.getId();
			String name = recipe.getName();
			Date date = recipe.getDate();
			stb.append(id + "\t" + name + "\t\t" + uname + "\t\t" + date
					+ "\r\n");

		}
		this.txtShowMy.setText(stb.toString());
		}
	

	private void jbtSend03MouseClicked(java.awt.event.MouseEvent evt) {
		int rid= Integer.valueOf(this.txtRecipeId.getText());
		List<Recipe> recipeList = fnc.ShowMy(nickName);
		String rname=fnc.getRecipe(rid);
		boolean flag=false;
		for (Recipe recipe : recipeList) {
			int id = recipe.getId();
			if(rid==id){
				flag=true;
				break;
			}
		}
		if(flag){
		String material=fnc.getMaterial(rid);
		String cook=fnc.getCook(rid);
		DetailFrame detailFrame=new DetailFrame(rid);
		detailFrame.Showdetail(rname,material,cook);
		detailFrame.setTitle("详情");
		detailFrame.setVisible(true);
		}else{
			JOptionPane.showMessageDialog(new JFrame(), "请输入列表中存在的编号!");
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ShowMyFrame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JButton jbtReturn03;
	private javax.swing.JButton jbtSend03;
	private javax.swing.JTextField txtRecipeId;
	private javax.swing.JTextArea txtShowMy;
	// End of variables declaration//GEN-END:variables

}