/*
 * ShowAllFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.cdw.java.recipe.Client;

import java.sql.Date;
import java.util.List;

import javax.swing.JTextArea;

import com.cdw.java.recipe.dao.CookDAO;
import com.cdw.java.recipe.dao.MaterialDAO;
import com.cdw.java.recipe.dao.RecipeDAO;
import com.cdw.java.recipe.dao.UserDAO;
import com.cdw.java.recipe.dao.Impl.CookDAOImpl;
import com.cdw.java.recipe.dao.Impl.MaterialDAOImpl;
import com.cdw.java.recipe.dao.Impl.RecipeDAOImpl;
import com.cdw.java.recipe.dao.Impl.UserDAOImpl;
import com.cdw.java.recipe.pojo.Recipe;

/**
 *
 * @author  __USER__
 */
public class ShowAllFrame extends javax.swing.JFrame {
	UserDAO userDAO = new UserDAOImpl();
	RecipeDAO recipeDAO = new RecipeDAOImpl();
	MaterialDAO materialDAO = new MaterialDAOImpl();
	CookDAO cookDAO = new CookDAOImpl();
	Function fnc = new Function();
	private String nickName;
	/** Creates new form ShowAllFrame */
	public ShowAllFrame(String nickName){
		this();
		this.nickName=nickName;
	}
	public ShowAllFrame() {
		//this.ReadList();
		initComponents();
	}
	

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		txtId = new javax.swing.JTextField();
		jbtSend01 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		txtList = new javax.swing.JTextArea();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel1.setText("\u8bf7\u8f93\u5165\u7f16\u53f7\uff1a");

		jbtSend01.setText("\u786e\u5b9a");
		jbtSend01.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jbtSend01MouseClicked(evt);
			}
		});

		jButton2.setText("\u8fd4\u56de");
		jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton2MouseClicked(evt);
			}
		});

		txtList.setColumns(20);
		txtList.setFont(new java.awt.Font("Monospaced", 0, 18));
		txtList.setForeground(new java.awt.Color(0, 0, 204));
		txtList.setRows(5);
		jScrollPane1.setViewportView(txtList);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(171, Short.MAX_VALUE)
								.addComponent(jLabel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										117,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(46, 46, 46)
								.addComponent(txtId,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										137,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(63, 63, 63)
								.addComponent(jbtSend01)
								.addGap(106, 106, 106)
								.addComponent(jButton2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										71,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(191, 191, 191))
				.addGroup(
						layout.createSequentialGroup()
								.addGap(51, 51, 51)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										866,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(48, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										375,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(18, 18,
																		18)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jButton2)
																				.addComponent(
																						jbtSend01)
																				.addComponent(
																						txtId,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(
														layout.createSequentialGroup()
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jLabel1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		52,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(42, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	public void ReadList() {
			
		List<Recipe> recipeList = fnc.ShowAll();
		StringBuilder stb=new StringBuilder("编号" + "\t" + "名称" + "\t\t\t" + "创建者" + "\t\t"
				+ "上传时间" + "\r\n");
		for (Recipe recipe : recipeList) {
			int id = recipe.getId();
			String name = recipe.getName();
			String uname = recipe.getUname();
			Date date = recipe.getDate();	
			stb.append(id + "\t" + name + "\t\t" + uname + "\t\t"
					+ date+"\r\n");
			
		}
		this.txtList.setText(stb.toString());
	}
	private void jbtSend01MouseClicked(java.awt.event.MouseEvent evt) {
		int rid= Integer.valueOf(this.txtId.getText());
		String rname=fnc.getRecipe(rid);		
		String material=fnc.getMaterial(rid);
		String cook=fnc.getCook(rid);
		DetailFrame detailFrame=new DetailFrame(rid);
		detailFrame.Showdetail(rname,material,cook);
		detailFrame.setTitle("详情");
		detailFrame.setVisible(true);
	}
	public void showResult(String stb){
		this.txtList.setText(stb);
	}

	//返回主界面或游客界面
	private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {
		String title = this.getTitle();
		if (title.equals("所有菜品列表")) {
			MainMenuFrame mainMenuFrame = new MainMenuFrame(nickName);
			mainMenuFrame.setTitle(nickName);
			mainMenuFrame.setVisible(true);
			this.setVisible(false);
		} else if(title.equals("搜索菜品")){			
			this.setVisible(false);
		}
		else {
			SearchFrame searchFrame=new SearchFrame();
			searchFrame.setTitle("----游客----");
			searchFrame.setVisible(true);
			this.setVisible(false);
		}

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ShowAllFrame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JButton jbtSend01;
	private javax.swing.JTextField txtId;
	private javax.swing.JTextArea txtList;
	// End of variables declaration//GEN-END:variables

}