/*
 * TouristFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.cdw.java.recipe.Client;

import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.net.Socket;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author  __USER__
 */
public class TouristFrame extends javax.swing.JFrame {

	/** Creates new form TouristFrame */
	public TouristFrame() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel9 = new javax.swing.JPanel();
		jbtUpLoad = new javax.swing.JButton();
		jbtDel = new javax.swing.JButton();
		jbtUpdate = new javax.swing.JButton();
		jbtShowMy = new javax.swing.JButton();
		jbtShowAll = new javax.swing.JButton();
		jbtSearch = new javax.swing.JButton();
		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel9.setBorder(new javax.swing.border.MatteBorder(null));

		jbtUpLoad.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jbtUpLoad.setForeground(new java.awt.Color(0, 0, 204));
		jbtUpLoad.setText("\u4e0a\u4f20\u83dc\u54c1");
		jbtUpLoad.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jbtUpLoadMouseClicked(evt);
			}
		});

		jbtDel.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jbtDel.setForeground(new java.awt.Color(0, 0, 255));
		jbtDel.setText("\u5220\u9664\u6211\u7684\u83dc\u54c1");
		jbtDel.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jbtDelMouseClicked(evt);
			}
		});

		jbtUpdate.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jbtUpdate.setForeground(new java.awt.Color(0, 0, 255));
		jbtUpdate.setText("\u4fee\u6539\u6211\u7684\u83dc\u54c1");
		jbtUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jbtUpdateMouseClicked(evt);
			}
		});
		jbtUpdate.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jbtUpdateActionPerformed(evt);
			}
		});

		jbtShowMy.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jbtShowMy.setForeground(new java.awt.Color(0, 0, 204));
		jbtShowMy.setText("\u67e5\u770b\u6211\u7684\u83dc\u54c1");
		jbtShowMy.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jbtShowMyMouseClicked(evt);
			}
		});

		jbtShowAll.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jbtShowAll.setForeground(new java.awt.Color(0, 0, 255));
		jbtShowAll.setText("\u67e5\u770b\u6240\u6709\u83dc\u54c1");
		jbtShowAll.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jbtShowAllMouseClicked(evt);
			}
		});

		jbtSearch.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jbtSearch.setForeground(new java.awt.Color(0, 0, 204));
		jbtSearch.setText("\u641c\u7d22\u83dc\u54c1");
		jbtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jbtSearchMouseClicked(evt);
			}
		});

		jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jButton1.setForeground(new java.awt.Color(255, 0, 0));
		jButton1.setText("\u9000\u51fa");
		jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton1MouseClicked(evt);
			}
		});

		javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(
				jPanel9);
		jPanel9.setLayout(jPanel9Layout);
		jPanel9Layout
				.setHorizontalGroup(jPanel9Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel9Layout
										.createSequentialGroup()
										.addGap(223, 223, 223)
										.addGroup(
												jPanel9Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jbtSearch,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																200,
																Short.MAX_VALUE)
														.addComponent(
																jbtShowAll,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																200,
																Short.MAX_VALUE)
														.addComponent(
																jbtDel,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																200,
																Short.MAX_VALUE)
														.addComponent(
																jbtUpdate,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																200,
																Short.MAX_VALUE)
														.addComponent(
																jbtShowMy,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																200,
																Short.MAX_VALUE)
														.addComponent(
																jbtUpLoad,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																200,
																Short.MAX_VALUE)
														.addComponent(
																jButton1,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																200,
																Short.MAX_VALUE))
										.addGap(263, 263, 263)));
		jPanel9Layout
				.setVerticalGroup(jPanel9Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel9Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jbtShowAll,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												53,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(26, 26, 26)
										.addComponent(
												jbtDel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												52,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(31, 31, 31)
										.addComponent(
												jbtUpdate,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												48,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(36, 36, 36)
										.addComponent(
												jbtShowMy,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												47,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(27, 27, 27)
										.addComponent(
												jbtUpLoad,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												55,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(28, 28, 28)
										.addComponent(
												jbtSearch,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												31, Short.MAX_VALUE)
										.addComponent(
												jButton1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												48,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {
		ExitsFrame exitsFrame = new ExitsFrame();
		exitsFrame.setTitle("ÌáÊ¾");
		exitsFrame.setVisible(true);
	}

	private void jbtSearchMouseClicked(java.awt.event.MouseEvent evt) {
		SearchFrame searchFrame = new SearchFrame();
		searchFrame.setTitle("----ÓÎ¿Í----");
		searchFrame.setVisible(true);
		this.setVisible(false);
	}

	private void jbtUpLoadMouseClicked(java.awt.event.MouseEvent evt) {
		JOptionPane.showMessageDialog(new JFrame(), "ÇëµÇÂ¼!");
	}

	private void jbtShowMyMouseClicked(java.awt.event.MouseEvent evt) {
		JOptionPane.showMessageDialog(new JFrame(), "ÇëµÇÂ¼!");
	}

	private void jbtUpdateMouseClicked(java.awt.event.MouseEvent evt) {
		JOptionPane.showMessageDialog(new JFrame(), "ÇëµÇÂ¼!");
	}

	private void jbtDelMouseClicked(java.awt.event.MouseEvent evt) {
		JOptionPane.showMessageDialog(new JFrame(), "ÇëµÇÂ¼!");
	}

	private void jbtShowAllMouseClicked(java.awt.event.MouseEvent evt) {

		ShowAllFrame showAllFrame = new ShowAllFrame();
		showAllFrame.ReadList();
		showAllFrame.setTitle("----ÓÎ¿Í----");
		showAllFrame.setVisible(true);
		this.setVisible(false);

	}

	private void jbtUpdateActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TouristFrame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JPanel jPanel9;
	private javax.swing.JButton jbtDel;
	private javax.swing.JButton jbtSearch;
	private javax.swing.JButton jbtShowAll;
	private javax.swing.JButton jbtShowMy;
	private javax.swing.JButton jbtUpLoad;
	private javax.swing.JButton jbtUpdate;
	// End of variables declaration//GEN-END:variables

}