/*
 * UpdateFrame1.java
 *
 * Created on __DATE__, __TIME__
 */

package com.cdw.java.recipe.Client;

import java.util.Date;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import com.cdw.java.recipe.dao.CookDAO;
import com.cdw.java.recipe.dao.MaterialDAO;
import com.cdw.java.recipe.dao.RecipeDAO;
import com.cdw.java.recipe.dao.UserDAO;
import com.cdw.java.recipe.dao.Impl.CookDAOImpl;
import com.cdw.java.recipe.dao.Impl.MaterialDAOImpl;
import com.cdw.java.recipe.dao.Impl.RecipeDAOImpl;
import com.cdw.java.recipe.dao.Impl.UserDAOImpl;

/**
 *
 * @author  __USER__
 */
public class UpdateFrame1 extends javax.swing.JFrame {
	private int rid;
	UserDAO userDAO = new UserDAOImpl();
	RecipeDAO recipeDAO = new RecipeDAOImpl();
	MaterialDAO materialDAO = new MaterialDAOImpl();
	CookDAO cookDAO = new CookDAOImpl();
	Function fnc = new Function();
	Date date = new Date();

	public UpdateFrame1(int rid) {
		this();
		this.rid = rid;		
	}

	/** Creates new form UpdateFrame1 */
	public UpdateFrame1() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		txtMaterial = new javax.swing.JTextArea();
		jScrollPane2 = new javax.swing.JScrollPane();
		txtCook = new javax.swing.JTextArea();
		jbtSend07 = new javax.swing.JButton();
		jButton1 = new javax.swing.JButton();
		txtRname = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel1.setText("\u540d\u79f0");

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel2.setText("\u914d\u6599");

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel3.setText("\u505a\u6cd5");

		txtMaterial.setColumns(20);
		txtMaterial.setFont(new java.awt.Font("Monospaced", 0, 18));
		txtMaterial.setRows(5);
		jScrollPane1.setViewportView(txtMaterial);

		txtCook.setColumns(20);
		txtCook.setFont(new java.awt.Font("Monospaced", 0, 18));
		txtCook.setRows(5);
		jScrollPane2.setViewportView(txtCook);

		jbtSend07.setText("\u786e\u5b9a");
		jbtSend07.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jbtSend07MouseClicked(evt);
			}
		});

		jButton1.setText("\u8fd4\u56de");
		jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton1MouseClicked(evt);
			}
		});

		txtRname.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		txtRname.setForeground(new java.awt.Color(255, 0, 0));
		txtRname.setText("\u540d\u79f0");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(61, 61, 61)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(
																		jLabel3)
																.addComponent(
																		jLabel2))
												.addComponent(jLabel1))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														txtRname,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														410, Short.MAX_VALUE)
												.addComponent(
														jScrollPane1,
														javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														410, Short.MAX_VALUE)
												.addComponent(
														jScrollPane2,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														410, Short.MAX_VALUE))
								.addGap(69, 69, 69))
				.addGroup(
						layout.createSequentialGroup().addGap(174, 174, 174)
								.addComponent(jbtSend07).addGap(91, 91, 91)
								.addComponent(jButton1)
								.addContainerGap(194, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														txtRname,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														48,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel1))
								.addGap(60, 60, 60)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel2)
												.addComponent(
														jScrollPane1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														145,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel3)
												.addComponent(
														jScrollPane2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														187,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jbtSend07,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														39,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jButton1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														36,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jbtSend07MouseClicked(java.awt.event.MouseEvent evt) {
		String material = this.txtMaterial.getText();
		String cook = this.txtCook.getText();
		java.sql.Date now = new java.sql.Date(date.getTime());
		boolean flag1 = fnc.UpdateRecipe(rid, now);
		boolean flag2 = fnc.UpdateMaterial(rid, material);
		boolean flag3 = fnc.UpdateCook(rid, cook);
		if (flag1 && flag2 || flag2 && flag3 || flag1 && flag3) {
			JOptionPane.showMessageDialog(new JFrame(), "修改成功!");
		} else {
			JOptionPane.showMessageDialog(new JFrame(), "修改失败!");
		}
	}
	public void RecipeName(String rname){
		this.txtRname.setText(rname);
	}
	private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {
		this.setVisible(false);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new UpdateFrame1().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JButton jbtSend07;
	private javax.swing.JTextArea txtCook;
	private javax.swing.JTextArea txtMaterial;
	private javax.swing.JLabel txtRname;
	// End of variables declaration//GEN-END:variables

}