/*
 * UploadFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.cdw.java.recipe.Client;

import java.util.Date;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import com.cdw.java.recipe.dao.CookDAO;
import com.cdw.java.recipe.dao.MaterialDAO;
import com.cdw.java.recipe.dao.RecipeDAO;
import com.cdw.java.recipe.dao.UserDAO;
import com.cdw.java.recipe.dao.Impl.CookDAOImpl;
import com.cdw.java.recipe.dao.Impl.MaterialDAOImpl;
import com.cdw.java.recipe.dao.Impl.RecipeDAOImpl;
import com.cdw.java.recipe.dao.Impl.UserDAOImpl;
import com.cdw.java.recipe.pojo.Cook;
import com.cdw.java.recipe.pojo.Material;
import com.cdw.java.recipe.pojo.Recipe;

/**
 *
 * @author  __USER__
 */
public class UploadFrame extends javax.swing.JFrame {
	private String nickName;
	UserDAO userDAO = new UserDAOImpl();
	RecipeDAO recipeDAO = new RecipeDAOImpl();
	MaterialDAO materialDAO = new MaterialDAOImpl();
	CookDAO cookDAO = new CookDAOImpl();
	Function fnc = new Function();
	Date date = new Date();

	public UploadFrame(String nickName) {
		this();
		this.nickName = nickName;
	}

	/** Creates new form UploadFrame */
	public UploadFrame() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		txtRecipeName = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		txtMatreial = new javax.swing.JTextArea();
		jScrollPane2 = new javax.swing.JScrollPane();
		txtCook = new javax.swing.JTextArea();
		jbtSend = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel1.setText("\u83dc\u540d");

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel2.setText("\u914d\u6599");

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel3.setText("\u505a\u6cd5");

		txtRecipeName.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		txtRecipeName.setForeground(new java.awt.Color(51, 0, 255));

		txtMatreial.setColumns(20);
		txtMatreial.setFont(new java.awt.Font("Monospaced", 0, 18));
		txtMatreial.setForeground(new java.awt.Color(51, 0, 204));
		txtMatreial.setRows(5);
		jScrollPane1.setViewportView(txtMatreial);

		txtCook.setColumns(20);
		txtCook.setFont(new java.awt.Font("Monospaced", 0, 18));
		txtCook.setForeground(new java.awt.Color(51, 0, 204));
		txtCook.setRows(5);
		jScrollPane2.setViewportView(txtCook);

		jbtSend.setText("\u4e0a\u4f20");
		jbtSend.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jbtSendMouseClicked(evt);
			}
		});

		jButton2.setText("\u8fd4\u56de");
		jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton2MouseClicked(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(38, 38,
																		38)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel3)
																				.addComponent(
																						jLabel2)
																				.addComponent(
																						jLabel1))
																.addGap(64, 64,
																		64)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						txtRecipeName,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						386,
																						Short.MAX_VALUE)
																				.addGroup(
																						layout.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																								.addComponent(
																										jScrollPane2)
																								.addComponent(
																										jScrollPane1,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										386,
																										Short.MAX_VALUE))))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(187,
																		187,
																		187)
																.addComponent(
																		jbtSend,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		79,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(107,
																		107,
																		107)
																.addComponent(
																		jButton2,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		76,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(94, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(47, 47, 47)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														txtRecipeName,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														41,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel1))
								.addGap(37, 37, 37)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel2)
												.addComponent(
														jScrollPane1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														135,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel3)
												.addComponent(
														jScrollPane2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														201,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(44, 44, 44)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addComponent(
														jButton2,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														jbtSend,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														44, Short.MAX_VALUE))
								.addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jbtSendMouseClicked(java.awt.event.MouseEvent evt) {
		String rname = this.txtRecipeName.getText();
		String metarialdetail = this.txtMatreial.getText();
		String cookdetail = this.txtCook.getText();
		java.sql.Date now = new java.sql.Date(date.getTime());
		Recipe recipe = new Recipe(rname, now, nickName);
		boolean flag = fnc.AddRecipe(recipe);
		if (flag) {
			recipe = recipeDAO.getRecipeByname(rname, nickName);
			int rid = recipe.getId();
			Material material = new Material(rname, metarialdetail, rid);
			Cook cook = new Cook(rname, cookdetail, rid);
			boolean flag2 = fnc.AddMaterial(material);
			boolean flag3 = fnc.AddCook(cook);
			if (flag && flag2 || flag2 && flag3 || flag && flag3) {
				JOptionPane.showMessageDialog(new JFrame(), "上传成功!");
			} else {
				JOptionPane.showMessageDialog(new JFrame(), "上传失败!");
			}
		}

	}

	private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {

		this.setVisible(false);

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new UploadFrame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JButton jbtSend;
	private javax.swing.JTextArea txtCook;
	private javax.swing.JTextArea txtMatreial;
	private javax.swing.JTextField txtRecipeName;
	// End of variables declaration//GEN-END:variables

}